/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
tasks.register("myproperties") {
    group = "custom"
    description = "generate properties"
    doLast {
        // also    def generatedFileDir = file("$buildDir/generated")
        //     outputs.dir generatedFileDir
        var folder = layout.buildDirectory.dir("generated");
        mkdir(folder)

        val propFile = folder.get().file("server.properties");
        propFile.asFile.writeText("gni")

        outputs.dir(folder)
    }   
}

// https://blog.gradle.org/introducing-incremental-build-support